const Attendances = [
  {
    id: "panel1",
    title: "Attendance to Validate",
    headers: [
      "Employee",
      "Batch",
      "Date",
      "Day",
      "Check-in",
      "In Date",
      "Check-out",
      "Out Date",
      "Shift",
      "WorkType",
      "Min Hour",
      "At Work",
      "Pending Hour",
      "Overtime",
      "Action",
      "Confirmation",
    ],
  },
  {
    id: "panel2",
    title: "OT Attendances",
    headers: [
      "Employee",
      "Batch",
      "Date",
      "Day",
      "Check-in",
      "In Date",
      "Check-out",
      "Out Date",
      "Shift",
      "WorkType",
      "Min Hour",
      "At Work",
      "Pending Hour",
      "Overtime",
      "Action",
      "Confirmation",
    ],
  },
  {
    id: "panel3",
    title: "Validate Attendances",
    headers: [
      "Employee",
      "Batch",
      "Date",
      "Day",
      "Check-in",
      "In Date",
      "Check-out",
      "Out Date",
      "Shift",
      "WorkType",
      "Min Hour",
      "At Work",
      "Pending Hour",
      "Overtime",
      "Action",
    ],
  },
];

export default Attendances;